### ISSUE TITLE
# Sprint 1

### ISSUE THREAD

**Issue by Suzzzzzy** [Suzzzzzy/Book_Study#1]
# Sprint 1
2023.08.07 ~ 2023.08.13

책 범위: **chapter 1 ~ chanpter 3** 

토론 날짜: 2023.08.14 월요일 09:00
토론 장소: B2 데카콘 / [Gather](https://cdn.arbeon.com/syncup)

- 토론 전까지, 논의 주제를 포함한 pull request 를 반드시 올려주세요!
- 서로의 pull request 에 자유롭게 코멘트를 남겨주세요

**Comment by mustard12** [comment]
네넵
