### ISSUE TITLE
Sprint 챕터 계획

### ISSUE THREAD

**Issue by Suzzzzzy** [Suzzzzzy/Book_Study#22]
현재까지 sprint 1 은 1~3 챕터, sprint 2는 4 ~7 챕터가 진행되었습니다

sprint 1 에서 1 ~ 4 챕터를 했어야 하는데 분배를 잘못 스타트 하는 바람에 ㅠㅜ 조금 빡세게 달려봐야할 것 같습니다!

sprint 3 : chapter 8 ~  11

sprint 4 : chapter 12 ~ 15

로 진행하겠습니다! sqrint 4가 제일 힘들것으로 예상되며.. 다른 아이디어가 있으시다면 코멘트 달아주세요!

**Comment by mustard12** [comment]
노우....힘들고 괴로워요... 하지만 로지가 시키시면 해야죠...

**Comment by mustard12** [comment]
헉 실수로 issue close시켜서 다시 리오픈입니다

**Comment by riley817** [comment]
모두모두 화이팅 💪🏻
