### ISSUE TITLE
게더타운 링크 요청

### ISSUE THREAD

**Issue by jongfeel** [Suzzzzzy/Book_Study#3]
게더타운 접속 주소도 여기에 공유해서 알려주시면 좋을 것 같습니다.

**Comment by riley817** [comment]
🥲 죄송합니다.

https://cdn.arbeon.com/syncup

**Comment by jongfeel** [comment]
아닙니다. 오늘은 안 하신 것 같아서, 이번주 금요일날 들어올께요.

**Comment by riley817** [comment]
네 멘탈 잡고 돌아오겠습니당...ㅎㅎㅎ 금요일날 뵙겠습니다 🥹
