### ISSUE TITLE
왜 Reviewers 리스트에 Riley는 안보일까요?

### ISSUE THREAD

**Issue by donis-y** [Suzzzzzy/Book_Study#6]
<img width="1552" alt="image" src="https://github.com/Suzzzzzy/Book_Study/assets/14763656/afb85801-fa57-4fcd-b1b1-bc627d97e34e">

왜 Assignees 리스트에 Riley는 안보일까요?

**Comment by jongfeel** [comment]
그건 이 repository에 멤버가 아니어서 그렇습니다. 초대를 수락하지 않은 상태인거죠.

**Comment by riley817** [comment]
헛 수락했습니다!

**Comment by donis-y** [comment]
@riley817 Reviewers 추가 완료!
 https://github.com/Suzzzzzy/Book_Study/pull/5
