### ISSUE TITLE
리뷰커밋 다시 부탁드립니다.

### ISSUE THREAD

**Issue by riley817** [Suzzzzzy/Book_Study#9]
@donis-y 
리아 PR에서 저 동기화 버튼을 제가 도니스것도 눌러버려서... 
다시 리뷰 화면으로 들어가서 메세지 암거나 쓰시고 다시 커밋 서브밋 버튼 누르시면 됩니다.. 
죄송합니다...

<img width="347" alt="image" src="https://github.com/Suzzzzzy/Book_Study/assets/41636282/f03cfaf8-645c-4e4f-bbb3-706c814ab446">

<img width="676" alt="image" src="https://github.com/Suzzzzzy/Book_Study/assets/41636282/368d9ebb-68e7-4201-b92a-fbbda1d872ea">

**Comment by donis-y** [comment]
음? 잘되어있는거 아닌가요??
뭔가 라일리가 말하고 나서 누르면 어떻게 되는건가해서 저 동기화 버튼을 눌러보진 않았어요.
<img width="1361" alt="image" src="https://github.com/Suzzzzzy/Book_Study/assets/14763656/31cb50a0-e2e3-4d62-971f-d80a6dcabcf6">

**Comment by donis-y** [comment]
Re-reqeust review군요. 
근데 괜찮은거 같은데요?
역시 누르진 않았어요 😁
<img width="385" alt="image" src="https://github.com/Suzzzzzy/Book_Study/assets/14763656/68ebb1cb-680d-4e38-85c9-11884dcb955d">

**Comment by riley817** [comment]
넵 갑자기 도니스가 승인목록에 빠져서 ㅎㅎㅎ 이슈 종료하겠습니다. 감사합니당
